---
- hosts: 172.31.18.125
  become: true
  tasks:
  - name: executing a linux command directly
    command: hostname -f
    register: display
  
  - name: display the result of previous task
    debug:
     msg: "{{display}}"
  
  - name: install git on the node
    apt:
     name: git
     state: present
    when: display.stderr==""
  
  - name: install tree on the node
    apt:
     name: tree
     state: present
    when: display.stderr!=""