---
- hosts : 172.31.18.125
  become: true
  tasks:
  - include_tasks: fileCreation.yml
  - name: copy file to the node Ansible_Node_ubuntu
    copy:
      src: testFile
      dest: /home/ubuntu/testFile.txt
    
  - name: install webserver on the node Ansible_Node_ubuntu
    apt:
     name: apache2
     state: present
  
  - name: copy index file on the node
    template:
     src: dynamicFiles.j2
     dest: /var/www/html/index.html

  - name: download internet files to the node  
    ansible.builtin.get_url:
     url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.0/bin/apache-tomcat-10.0.0-deployer.tar.gz
     dest: /home/ubuntu/apache-tomcat-10.0.0-deployer.tar.gz
     force_basic_auth: yes
