---
- hosts: webServers
  become: true
  tasks:
   - name: install java on ubuntu nodes
     apt:
       name:
       state: present
     when: ansible_os_family== "Debian"
      
   - name: install java on redhat nodes
     dnf:
       name: 
       state: present
     when: ansible_os_family== "RedHat"

